config/routes.rb
Rails.application.routes.draw do
	root to: 'users#home', via: :get
	get 'auth/facebook', as: "auth_provider"
	get 'auth/facebook/callback', to: 'users#login', as: "signin"

    post 'reserve', to: 'reservations#create'

end

app/models/item.rb
class Item < ActiveRecord::Base
    has_many :reservations
    has_many :users, through: :reservations

    def position(reservations)
        result=reservations.find_by(item: self)
        if result.nil?
            false
        else
            result.queue
        end
    end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    belongs_to :user
    belongs_to :item

  validates :queue, uniqueness: { scope: :item, message: "Should not have duplicated queue position for one item!!" }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :items, through: :reservations

  validates :fb_id, uniqueness: true

  def self.basic_info_from_fb(auth)
    access_token = auth['token']
    facebook = Koala::Facebook::API.new(access_token)
    facebook.get_object("me?fields=name,picture")
  end

  def self.friends_from_fb(auth)
    access_token = auth['token']
    facebook = Koala::Facebook::API.new(access_token)
    facebook.get_connections("me", "friends")
  end
end


# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  fb_id      :string
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  name       :string
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    def create
        item_id = params[:ii]
        cu = session[:current_user]['id']
        np = Reservation.where(item_id: item_id).count + 1
        Reservation.create(queue: np, user: User.find(cu), item: Item.find(item_id))
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signin?
    !@current_user.nil?
  end

  def home
      @users = User.all
      @current_user = session[:current_user]
      if signin?
        @items = Item.all
        cu = User.find(@current_user['id'])
        @re = Reservation.where(user: cu)
        render
      else
        redirect_to auth_provider_url
      end
  end

  def login
    @basic_info = User.basic_info_from_fb(request.env['omniauth.auth']['credentials'])
    @friends = User.friends_from_fb(request.env['omniauth.auth']['credentials'])
    @user = User.create_with(name: @basic_info['name'], photo: @basic_info['picture']['data']['url']).find_or_create_by(fb_id: @basic_info['id']) 
    session[:current_user] ||= @user;
    @signed_in = signin?
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_footer.html.erb
<footer class="container footer">
<small>
    created by Terry Fong
</small>
<ul class="nav navbar-nav navbar-right">
    <li><a href="about.html">About</a></li>
    <li><a href="career.html">Career</a></li>
</ul>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuanHai</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
                <%= yield %>
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/reservations/create.html.erb
<p>
<%= @item_id %> is clicked.
</p><p>
Current user:
<%= @cu %>
</p><p>
next position: <%= @np %>
</p>

app/views/users/home.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
            <a class="navbar-brand" href="/">港仔の出清台大</a>
            <ul class="nav navbar-nav navbar-right">
                <li><%= image_tag(@current_user['photo']) %></li>
                <li><a href="#"><%= @current_user['name'] %></a></li>
            </ul>
    </div>
</nav>
    <div id="main-container" class="container">
        <div class="row">
            <div class"col-xs-12">
                <% flash.each do |name, msg| %>
                    <%= content_tag :div, msg, class: "alert alert-#{name}" %>
                <% end %>
            </div>
        </div>
        <div class="row">
            <div class"col-xs-12">
<div id="userhome-container" class="container">
    <div class="row">
        <table class="table table-hover">
            <tr>
                <th>  </th>
                <th>名稱</th>
                <th>價錢</th>
                <th>保留／排位</th>
            </tr>
            <% user=@current_user %>
            <% @items.each do |item| %>
                <tr>
                    <td><%= image_tag(item.photo, size: "200") %></td>
                    <td><%= item.name %></td>
                    <td><%= item.price %></td>
                    <td>
                        <% pos = item.position(@re) %>
                        <% if pos %>
                            商品已保留。排位：<%= pos %>
                        <% else %>
                         <%= button_to "reserve", reserve_path, params: {ii: item.id}  %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>
            </div>
        </div>
    </div>

app/views/users/login.html.erb
<p>
<%= image_tag @user['picture']['data']['url'].to_s %>
<%= @user['name'] %>
</p>
<p>
<% @friends.each do |fd| %> 
	<%= p fd %>
<% end %>
</p>

app/views/users/unused.html.erb
<h1>User's homepage</h1>
<p>
<%= image_tag @basic_info['picture']['data']['url'].to_s %>
<%= @basic_info %>
</p>
<p>
<ul>
<% @friends.each do |fd| %> 
	<li><%= fd['name'] %> ::::: <%= fd['id'] %></li>
<% end %>
</ul>
</p>